// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: x/provider/types/query_oscript.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// OracleScriptInfoReq is the request type for the Query/OracleScriptInfo RPC method
type OracleScriptInfoReq struct {
	// address is the address of the contract to query
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (m *OracleScriptInfoReq) Reset()         { *m = OracleScriptInfoReq{} }
func (m *OracleScriptInfoReq) String() string { return proto.CompactTextString(m) }
func (*OracleScriptInfoReq) ProtoMessage()    {}
func (*OracleScriptInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4abb115fe145c3e, []int{0}
}
func (m *OracleScriptInfoReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OracleScriptInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OracleScriptInfoReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OracleScriptInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OracleScriptInfoReq.Merge(m, src)
}
func (m *OracleScriptInfoReq) XXX_Size() int {
	return m.Size()
}
func (m *OracleScriptInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_OracleScriptInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_OracleScriptInfoReq proto.InternalMessageInfo

func (m *OracleScriptInfoReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// OracleScriptInfoRes is the response type for the Query/OracleScriptInfo RPC method
type OracleScriptInfoRes struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Owner is the address who is allowed to make further changes to the oracle script.
	Owner       github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,2,opt,name=owner,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"owner,omitempty"`
	Contract    string                                        `protobuf:"bytes,3,opt,name=contract,proto3" json:"contract,omitempty"`
	Description string                                        `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Fees        github_com_cosmos_cosmos_sdk_types.Coins      `protobuf:"bytes,5,rep,name=fees,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"fees" json:"fees"`
	DSources    []string                                      `protobuf:"bytes,6,rep,name=d_sources,json=dSources,proto3" json:"d_sources,omitempty" json:"data_sources"`
	TCases      []string                                      `protobuf:"bytes,7,rep,name=t_cases,json=tCases,proto3" json:"t_cases,omitempty" json:"test_cases"`
}

func (m *OracleScriptInfoRes) Reset()         { *m = OracleScriptInfoRes{} }
func (m *OracleScriptInfoRes) String() string { return proto.CompactTextString(m) }
func (*OracleScriptInfoRes) ProtoMessage()    {}
func (*OracleScriptInfoRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4abb115fe145c3e, []int{1}
}
func (m *OracleScriptInfoRes) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OracleScriptInfoRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OracleScriptInfoRes.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OracleScriptInfoRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OracleScriptInfoRes.Merge(m, src)
}
func (m *OracleScriptInfoRes) XXX_Size() int {
	return m.Size()
}
func (m *OracleScriptInfoRes) XXX_DiscardUnknown() {
	xxx_messageInfo_OracleScriptInfoRes.DiscardUnknown(m)
}

var xxx_messageInfo_OracleScriptInfoRes proto.InternalMessageInfo

func (m *OracleScriptInfoRes) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OracleScriptInfoRes) GetOwner() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *OracleScriptInfoRes) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *OracleScriptInfoRes) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *OracleScriptInfoRes) GetFees() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Fees
	}
	return nil
}

func (m *OracleScriptInfoRes) GetDSources() []string {
	if m != nil {
		return m.DSources
	}
	return nil
}

func (m *OracleScriptInfoRes) GetTCases() []string {
	if m != nil {
		return m.TCases
	}
	return nil
}

// ListOracleScriptsReq is the request type for the Query/ListOracleScripts RPC method
type ListOracleScriptsReq struct {
}

func (m *ListOracleScriptsReq) Reset()         { *m = ListOracleScriptsReq{} }
func (m *ListOracleScriptsReq) String() string { return proto.CompactTextString(m) }
func (*ListOracleScriptsReq) ProtoMessage()    {}
func (*ListOracleScriptsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4abb115fe145c3e, []int{2}
}
func (m *ListOracleScriptsReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListOracleScriptsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListOracleScriptsReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListOracleScriptsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOracleScriptsReq.Merge(m, src)
}
func (m *ListOracleScriptsReq) XXX_Size() int {
	return m.Size()
}
func (m *ListOracleScriptsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOracleScriptsReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListOracleScriptsReq proto.InternalMessageInfo

// ListOracleScriptsRes is the response type for the Query/ListOracleScripts RPC method
type ListOracleScriptsRes struct {
	OracleScripts []OracleScript `protobuf:"bytes,1,rep,name=OracleScripts,proto3" json:"OracleScripts" json:"oracle_scripts"`
	Count         int64          `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (m *ListOracleScriptsRes) Reset()         { *m = ListOracleScriptsRes{} }
func (m *ListOracleScriptsRes) String() string { return proto.CompactTextString(m) }
func (*ListOracleScriptsRes) ProtoMessage()    {}
func (*ListOracleScriptsRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4abb115fe145c3e, []int{3}
}
func (m *ListOracleScriptsRes) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListOracleScriptsRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListOracleScriptsRes.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListOracleScriptsRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOracleScriptsRes.Merge(m, src)
}
func (m *ListOracleScriptsRes) XXX_Size() int {
	return m.Size()
}
func (m *ListOracleScriptsRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOracleScriptsRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListOracleScriptsRes proto.InternalMessageInfo

func (m *ListOracleScriptsRes) GetOracleScripts() []OracleScript {
	if m != nil {
		return m.OracleScripts
	}
	return nil
}

func (m *ListOracleScriptsRes) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*OracleScriptInfoReq)(nil), "oraichain.orai.provider.OracleScriptInfoReq")
	proto.RegisterType((*OracleScriptInfoRes)(nil), "oraichain.orai.provider.OracleScriptInfoRes")
	proto.RegisterType((*ListOracleScriptsReq)(nil), "oraichain.orai.provider.ListOracleScriptsReq")
	proto.RegisterType((*ListOracleScriptsRes)(nil), "oraichain.orai.provider.ListOracleScriptsRes")
}

func init() {
	proto.RegisterFile("x/provider/types/query_oscript.proto", fileDescriptor_e4abb115fe145c3e)
}

var fileDescriptor_e4abb115fe145c3e = []byte{
	// 516 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x41, 0x6f, 0xd3, 0x30,
	0x18, 0x6d, 0xe8, 0xd6, 0xad, 0x2e, 0x1c, 0xc8, 0x3a, 0x16, 0x2a, 0x94, 0x54, 0x11, 0x48, 0x05,
	0x69, 0x8e, 0x0a, 0x9c, 0xb8, 0xa0, 0x75, 0x48, 0x08, 0x09, 0x09, 0x29, 0xbb, 0x71, 0xa9, 0x5c,
	0xc7, 0xeb, 0x0c, 0xab, 0xbf, 0xd6, 0x9f, 0x3b, 0x98, 0xb8, 0x73, 0xe6, 0x6f, 0xc0, 0x2f, 0xd9,
	0x71, 0x47, 0x4e, 0x01, 0xb5, 0xff, 0xa0, 0x47, 0x4e, 0x28, 0x76, 0x36, 0xb5, 0x50, 0x24, 0x2e,
	0xc9, 0xb3, 0xdf, 0x7b, 0xf6, 0xcb, 0xcb, 0x47, 0xee, 0x7f, 0x4c, 0xc6, 0x1a, 0xce, 0x64, 0x26,
	0x74, 0x62, 0xce, 0xc7, 0x02, 0x93, 0xc9, 0x54, 0xe8, 0xf3, 0x3e, 0x20, 0xd7, 0x72, 0x6c, 0xe8,
	0x58, 0x83, 0x01, 0x7f, 0x0f, 0x34, 0x93, 0xfc, 0x84, 0x49, 0x45, 0x0b, 0x44, 0xaf, 0x2c, 0xad,
	0xe6, 0x10, 0x86, 0x60, 0x35, 0x49, 0x81, 0x9c, 0xbc, 0x15, 0x72, 0xc0, 0x11, 0x60, 0x32, 0x60,
	0x28, 0x92, 0xb3, 0xee, 0x40, 0x18, 0xd6, 0x4d, 0x38, 0x48, 0x55, 0xf2, 0xf7, 0x86, 0x00, 0xc3,
	0x53, 0x91, 0xb0, 0xb1, 0x4c, 0x98, 0x52, 0x60, 0x98, 0x91, 0xa0, 0xb0, 0x64, 0xa3, 0xbf, 0x22,
	0xd9, 0x67, 0x1f, 0x4a, 0x41, 0xfc, 0x90, 0xec, 0xbc, 0xd1, 0x8c, 0x9f, 0x8a, 0x23, 0x9b, 0xf1,
	0x95, 0x3a, 0x86, 0x54, 0x4c, 0x7c, 0x9f, 0x6c, 0x28, 0x36, 0x12, 0x81, 0xd7, 0xf6, 0x3a, 0xf5,
	0xd4, 0xe2, 0xf8, 0x73, 0x75, 0x9d, 0x16, 0xd7, 0x69, 0xfd, 0x97, 0x64, 0x13, 0x3e, 0x28, 0xa1,
	0x83, 0x1b, 0x6d, 0xaf, 0x73, 0xb3, 0xd7, 0xfd, 0x95, 0x47, 0xfb, 0x43, 0x69, 0x4e, 0xa6, 0x03,
	0xca, 0x61, 0x94, 0x94, 0xdf, 0xe4, 0x5e, 0xfb, 0x98, 0xbd, 0x77, 0xb1, 0xe8, 0x01, 0xe7, 0x07,
	0x59, 0xa6, 0x05, 0x62, 0xea, 0xfc, 0x7e, 0x8b, 0x6c, 0x73, 0x50, 0x46, 0x33, 0x6e, 0x82, 0xaa,
	0xbd, 0xe0, 0x7a, 0xed, 0xb7, 0x49, 0x23, 0x13, 0xae, 0x5b, 0x09, 0x2a, 0xd8, 0xb0, 0xf4, 0xf2,
	0x96, 0xaf, 0xc8, 0xc6, 0xb1, 0x10, 0x18, 0x6c, 0xb6, 0xab, 0x9d, 0xc6, 0xe3, 0xbb, 0xd4, 0x5d,
	0x48, 0x8b, 0x2e, 0x69, 0xd9, 0x25, 0x3d, 0x04, 0xa9, 0x7a, 0xcf, 0x2f, 0xf2, 0xa8, 0xb2, 0xc8,
	0xa3, 0xc6, 0x3b, 0x04, 0xf5, 0x2c, 0x2e, 0x4c, 0xf1, 0xb7, 0x1f, 0x51, 0xe7, 0x3f, 0x32, 0x17,
	0x7e, 0x4c, 0xed, 0x3d, 0xfe, 0x53, 0x52, 0xcf, 0xfa, 0x08, 0x53, 0xcd, 0x05, 0x06, 0xb5, 0x76,
	0xb5, 0x53, 0xef, 0xed, 0x2d, 0xf2, 0x68, 0xc7, 0x9d, 0x9a, 0x31, 0xc3, 0xae, 0xd8, 0x38, 0xdd,
	0xce, 0x8e, 0x1c, 0xf4, 0x29, 0xd9, 0x32, 0x7d, 0xce, 0x50, 0x60, 0xb0, 0x65, 0x3d, 0xbb, 0x8b,
	0x3c, 0xba, 0xed, 0x3c, 0x46, 0x60, 0xc9, 0xc5, 0x69, 0xcd, 0x1c, 0x5a, 0x70, 0x87, 0x34, 0x5f,
	0x4b, 0x34, 0xcb, 0xff, 0x02, 0x53, 0x31, 0x89, 0xbf, 0x7a, 0x6b, 0x09, 0xf4, 0x3f, 0x91, 0x5b,
	0x2b, 0x7b, 0x81, 0x67, 0xfb, 0x78, 0x40, 0xff, 0x31, 0x8a, 0x74, 0x59, 0xdd, 0xa3, 0x45, 0x37,
	0xb3, 0x3c, 0x5a, 0x3d, 0x63, 0x91, 0x47, 0xbb, 0x2e, 0x22, 0xd8, 0xed, 0xbe, 0x6b, 0x1d, 0xe3,
	0x74, 0x55, 0xe7, 0x37, 0xc9, 0x26, 0x87, 0xa9, 0x32, 0x76, 0x14, 0xaa, 0xa9, 0x5b, 0xf4, 0x5e,
	0x5c, 0xcc, 0x42, 0xef, 0x72, 0x16, 0x7a, 0x3f, 0x67, 0xa1, 0xf7, 0x65, 0x1e, 0x56, 0x2e, 0xe7,
	0x61, 0xe5, 0xfb, 0x3c, 0xac, 0xbc, 0x7d, 0xb4, 0xd4, 0xf9, 0x75, 0x3e, 0x8b, 0x92, 0x3f, 0x87,
	0x79, 0x50, 0xb3, 0x43, 0xfc, 0xe4, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x24, 0x1b, 0x4d, 0xc3,
	0x7a, 0x03, 0x00, 0x00,
}

func (m *OracleScriptInfoReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OracleScriptInfoReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OracleScriptInfoReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintQueryOscript(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *OracleScriptInfoRes) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OracleScriptInfoRes) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OracleScriptInfoRes) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TCases) > 0 {
		for iNdEx := len(m.TCases) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.TCases[iNdEx])
			copy(dAtA[i:], m.TCases[iNdEx])
			i = encodeVarintQueryOscript(dAtA, i, uint64(len(m.TCases[iNdEx])))
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.DSources) > 0 {
		for iNdEx := len(m.DSources) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.DSources[iNdEx])
			copy(dAtA[i:], m.DSources[iNdEx])
			i = encodeVarintQueryOscript(dAtA, i, uint64(len(m.DSources[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.Fees) > 0 {
		for iNdEx := len(m.Fees) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Fees[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQueryOscript(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintQueryOscript(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Contract) > 0 {
		i -= len(m.Contract)
		copy(dAtA[i:], m.Contract)
		i = encodeVarintQueryOscript(dAtA, i, uint64(len(m.Contract)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintQueryOscript(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintQueryOscript(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ListOracleScriptsReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListOracleScriptsReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListOracleScriptsReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *ListOracleScriptsRes) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListOracleScriptsRes) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListOracleScriptsRes) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Count != 0 {
		i = encodeVarintQueryOscript(dAtA, i, uint64(m.Count))
		i--
		dAtA[i] = 0x10
	}
	if len(m.OracleScripts) > 0 {
		for iNdEx := len(m.OracleScripts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.OracleScripts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQueryOscript(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQueryOscript(dAtA []byte, offset int, v uint64) int {
	offset -= sovQueryOscript(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *OracleScriptInfoReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovQueryOscript(uint64(l))
	}
	return n
}

func (m *OracleScriptInfoRes) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovQueryOscript(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovQueryOscript(uint64(l))
	}
	l = len(m.Contract)
	if l > 0 {
		n += 1 + l + sovQueryOscript(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovQueryOscript(uint64(l))
	}
	if len(m.Fees) > 0 {
		for _, e := range m.Fees {
			l = e.Size()
			n += 1 + l + sovQueryOscript(uint64(l))
		}
	}
	if len(m.DSources) > 0 {
		for _, s := range m.DSources {
			l = len(s)
			n += 1 + l + sovQueryOscript(uint64(l))
		}
	}
	if len(m.TCases) > 0 {
		for _, s := range m.TCases {
			l = len(s)
			n += 1 + l + sovQueryOscript(uint64(l))
		}
	}
	return n
}

func (m *ListOracleScriptsReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *ListOracleScriptsRes) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.OracleScripts) > 0 {
		for _, e := range m.OracleScripts {
			l = e.Size()
			n += 1 + l + sovQueryOscript(uint64(l))
		}
	}
	if m.Count != 0 {
		n += 1 + sovQueryOscript(uint64(m.Count))
	}
	return n
}

func sovQueryOscript(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQueryOscript(x uint64) (n int) {
	return sovQueryOscript(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *OracleScriptInfoReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQueryOscript
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OracleScriptInfoReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OracleScriptInfoReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryOscript
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQueryOscript
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQueryOscript
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQueryOscript(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQueryOscript
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQueryOscript
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OracleScriptInfoRes) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQueryOscript
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OracleScriptInfoRes: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OracleScriptInfoRes: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryOscript
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQueryOscript
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQueryOscript
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryOscript
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQueryOscript
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQueryOscript
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = append(m.Owner[:0], dAtA[iNdEx:postIndex]...)
			if m.Owner == nil {
				m.Owner = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Contract", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryOscript
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQueryOscript
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQueryOscript
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Contract = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryOscript
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQueryOscript
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQueryOscript
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fees", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryOscript
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQueryOscript
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQueryOscript
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Fees = append(m.Fees, types.Coin{})
			if err := m.Fees[len(m.Fees)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DSources", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryOscript
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQueryOscript
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQueryOscript
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DSources = append(m.DSources, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TCases", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryOscript
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQueryOscript
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQueryOscript
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TCases = append(m.TCases, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQueryOscript(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQueryOscript
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQueryOscript
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListOracleScriptsReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQueryOscript
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListOracleScriptsReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListOracleScriptsReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQueryOscript(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQueryOscript
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQueryOscript
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListOracleScriptsRes) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQueryOscript
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListOracleScriptsRes: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListOracleScriptsRes: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OracleScripts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryOscript
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQueryOscript
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQueryOscript
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OracleScripts = append(m.OracleScripts, OracleScript{})
			if err := m.OracleScripts[len(m.OracleScripts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryOscript
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQueryOscript(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQueryOscript
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQueryOscript
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQueryOscript(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQueryOscript
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQueryOscript
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQueryOscript
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQueryOscript
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQueryOscript
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQueryOscript
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQueryOscript        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQueryOscript          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQueryOscript = fmt.Errorf("proto: unexpected end of group")
)
