version: "3.3"
services:
  orai:
    container_name: orai_node
    image: oraichain/foundation-orai:0.42.2-alpine-dev
    working_dir: /workspace
    tty: true
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 3317:1317
      - 36656:26656
      - 36657:26657
      - 3090:9090
    cap_add:
      - SYS_PTRACE
    env_file:
      - orai.env
    volumes:
      - ./:/workspace
      - oraivisor:/root/oraivisor

  proto:
    image: cosmwasm/prototools-docker
    tty: true
    volumes:
      - ./:/work
volumes:
  oraivisor: null
